### ISSUE TITLE
Correct process to handle Statamic's Pagination

### ISSUE THREAD

**Issue by kev2480** [robertguss/gatsby-source-statamic#9]
Coming across an issue where I'm only retrieving Statamics default pagination limit of 25 when using the collection / asset fields. Is this the case that the plugin will only ever fetch the first 25 and I won't be able to change the limit in my Graphql queries?

Am I correct in assuming that to query more entries I will have to use the customUrls field and set the limit manually?

**Comment by robertguss** [comment]
Hi @kev2480. Yes, you will need to use the custom urls field and add query params to the url to adjust the pagination. You can see how to that that here: https://statamic.dev/content-api#pagination

Let me know if you have any issues, as it has been a while since I wrote this plugin.

Just an fyi... Statamic recently released a preview version where they are integrating GraphQL natively so I am working on writing a new plugin to take advantage of this. This might be a better option in the future than doing everything via rest.

**Comment by kev2480** [comment]
Thanks @robertguss - that helps. I'm looking forward to seeing the work on that!
